name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Install TeX Live
        run: sudo apt update && sudo apt install biber latexmk texlive texlive-bibtex-extra texlive-fonts-extra texlive-lang-german texlive-latex-extra texlive-luatex
      - name: Set up Git repository
        uses: actions/checkout@v5
      - name: Compile LaTeX document
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: Bewerbung.pdf
          path: out/Bewerbung.pdf
