name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          args: -pdf --output-directory=out
          root_file: Bewerbung.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bewerbung.pdf.zip
          path: out/Bewerbung.pdf
